import type { Agent } from './types';

/**
 * Priority emoji mapping
 */
const PRIORITY_EMOJI: Record<Agent['priority'], string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🟢'
};

/**
 * Generate agent markdown file content
 */
export function generateAgentMarkdown(agent: Agent, projectName: string): string {
  const priorityEmoji = PRIORITY_EMOJI[agent.priority];
  const priorityText = agent.priority.toUpperCase();

  return `# ${agent.name}

**Role:** ${agent.role}

**Priority:** ${priorityEmoji} ${priorityText}

---

## Responsibilities

${agent.responsibilities.map(r => `- ${r}`).join('\n')}

## MCP Access

${agent.mcpAccess.map(mcp => `- \`${mcp}\``).join('\n')}

## Collaborates With

${agent.collaboratesWith.map(a => `- ${a}`).join('\n')}

## Success Criteria

${agent.responsibilities.map(r => `- [ ] ${r}`).join('\n')}

---

**Project:** ${projectName}
**Generated by:** Project Generator Pro
**Date:** ${new Date().toISOString()}
`;
}
