import type { APIRoute } from 'astro';
import type { APIResponse } from '../../lib/types';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

/**
 * POST /api/github-push
 *
 * Creates GitHub repository and pushes initial commit using GitHub MCP
 *
 * Request Body:
 * - projectName: string (original project name)
 * - sanitizedName: string (sanitized project name for repo)
 * - projectPath: string (absolute path to project directory)
 * - description: string (project description)
 *
 * Response:
 * - 200: { success: true, data: { githubUrl, repoName } }
 * - 400: { success: false, error: string }
 * - 401: { success: false, error: "Unauthorized" }
 * - 500: { success: false, error: string }
 */
export const POST: APIRoute = async ({ request, cookies }) => {
  try {
    // Authentication check
    const authToken = cookies.get('auth_token');
    if (authToken?.value !== 'authenticated') {
      return new Response(JSON.stringify({
        success: false,
        error: 'Unauthorized'
      } as APIResponse), {
        status: 401,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    // Parse request body
    const body = await request.json();
    const { projectName, sanitizedName, projectPath, description } = body;

    // Validate required fields
    if (!sanitizedName || !projectPath) {
      return new Response(JSON.stringify({
        success: false,
        error: 'Missing required fields: sanitizedName, projectPath'
      } as APIResponse), {
        status: 400,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    // Sanitize repository name (GitHub requirements: lowercase, hyphens only, no special chars)
    const repoName = sanitizedName
      .toLowerCase()
      .replace(/[^a-z0-9-]/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '') // Remove leading/trailing hyphens
      .substring(0, 100); // GitHub max length

    if (!repoName) {
      return new Response(JSON.stringify({
        success: false,
        error: 'Invalid repository name after sanitization'
      } as APIResponse), {
        status: 400,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    // Prepare GitHub operations
    const githubOperations = {
      // Step 1: Create GitHub repository
      createRepository: {
        name: repoName,
        private: true, // Private by default
        description: description || `${projectName} - Generated by Project Generator Pro`,
        autoInit: false, // Don't initialize (we have files already)
        hasIssues: true,
        hasProjects: false,
        hasWiki: false
      },

      // Step 2: Git initialization and push commands
      gitCommands: [
        {
          command: 'git init',
          cwd: projectPath,
          description: 'Initialize git repository'
        },
        {
          command: 'git add .',
          cwd: projectPath,
          description: 'Stage all files'
        },
        {
          command: 'git commit -m "Initial commit from Project Generator Pro\n\nProject: ' + projectName + '\nGenerated: ' + new Date().toISOString() + '\n\nCreated with Project Generator Pro - https://project.n8naccess.xyz"',
          cwd: projectPath,
          description: 'Create initial commit'
        },
        {
          command: 'git branch -M main',
          cwd: projectPath,
          description: 'Rename branch to main'
        },
        // Remote add and push will be added after repo creation with actual URL
      ]
    };

    // Get GitHub credentials from environment
    const githubUsername = process.env.GITHUB_USERNAME || 'Smietje77';
    const githubToken = process.env.GITHUB_TOKEN;

    if (!githubToken) {
      return new Response(JSON.stringify({
        success: false,
        error: 'GitHub token not configured. Please set GITHUB_TOKEN environment variable.'
      } as APIResponse), {
        status: 500,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    // Construct repository URL
    const repoUrl = `https://github.com/${githubUsername}/${repoName}.git`;
    const htmlUrl = `https://github.com/${githubUsername}/${repoName}`;

    try {
      // Step 1: Create GitHub repository using GitHub API
      console.log('[GitHub Push] Creating repository:', repoName);
      const createRepoResponse = await fetch('https://api.github.com/user/repos', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${githubToken}`,
          'Accept': 'application/vnd.github.v3+json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: repoName,
          private: true,
          // GitHub limits descriptions to 350 characters
          description: (description || `${projectName} - Generated by Project Generator Pro`).substring(0, 350),
          has_issues: true,
          has_projects: false,
          has_wiki: false,
          auto_init: false
        })
      });

      if (!createRepoResponse.ok) {
        const errorData = await createRepoResponse.json();
        console.error('[GitHub Push] Failed to create repository:', errorData);

        // Check if repository already exists
        if (errorData.errors?.[0]?.message?.includes('already exists')) {
          return new Response(JSON.stringify({
            success: false,
            error: `Repository "${repoName}" already exists. Please use a different name or delete the existing repository.`
          } as APIResponse), {
            status: 400,
            headers: { 'Content-Type': 'application/json' }
          });
        }

        throw new Error(errorData.message || 'Failed to create GitHub repository');
      }

      const repoData = await createRepoResponse.json();
      console.log('[GitHub Push] Repository created:', repoData.html_url);

      // Step 2: Initialize git and push
      console.log('[GitHub Push] Initializing git in:', projectPath);

      // Configure git with credentials
      await execAsync(`git config --global user.name "${githubUsername}"`, { cwd: projectPath });
      await execAsync(`git config --global user.email "${githubUsername}@users.noreply.github.com"`, { cwd: projectPath });

      // Initialize repository
      await execAsync('git init', { cwd: projectPath });
      console.log('[GitHub Push] Git initialized');

      // Add all files
      await execAsync('git add .', { cwd: projectPath });
      console.log('[GitHub Push] Files staged');

      // Create commit
      const commitMessage = `Initial commit from Project Generator Pro

Project: ${projectName}
Generated: ${new Date().toISOString()}

Created with Project Generator Pro - https://project.n8naccess.xyz`;

      await execAsync(`git commit -m "${commitMessage.replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`, { cwd: projectPath });
      console.log('[GitHub Push] Commit created');

      // Set main branch
      await execAsync('git branch -M main', { cwd: projectPath });
      console.log('[GitHub Push] Branch renamed to main');

      // Add remote with authentication in URL
      const authenticatedUrl = `https://${githubToken}@github.com/${githubUsername}/${repoName}.git`;
      await execAsync(`git remote add origin ${authenticatedUrl}`, { cwd: projectPath });
      console.log('[GitHub Push] Remote added');

      // Push to GitHub
      await execAsync('git push -u origin main', { cwd: projectPath });
      console.log('[GitHub Push] Successfully pushed to GitHub');

      // Return success response
      return new Response(JSON.stringify({
        success: true,
        data: {
          repoName,
          githubUrl: htmlUrl,
          cloneUrl: repoUrl,
          message: 'Successfully created GitHub repository and pushed initial commit!'
        }
      } as APIResponse), {
        status: 200,
        headers: { 'Content-Type': 'application/json' }
      });

    } catch (execError) {
      console.error('[GitHub Push] Execution error:', execError);

      // Try to clean up remote if it was added
      try {
        await execAsync('git remote remove origin', { cwd: projectPath });
      } catch (cleanupError) {
        // Ignore cleanup errors
      }

      return new Response(JSON.stringify({
        success: false,
        error: execError instanceof Error ? execError.message : 'Failed to push to GitHub. Please check your credentials and try again.'
      } as APIResponse), {
        status: 500,
        headers: { 'Content-Type': 'application/json' }
      });
    }

  } catch (error) {
    console.error('GitHub push error:', error);

    return new Response(JSON.stringify({
      success: false,
      error: error instanceof Error ? error.message : 'GitHub push failed. Please try again.'
    } as APIResponse), {
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
};

/**
 * GET /api/github-push/status
 *
 * Check GitHub repository status
 */
export const GET: APIRoute = async ({ url, cookies }) => {
  try {
    // Authentication check
    const authToken = cookies.get('auth_token');
    if (authToken?.value !== 'authenticated') {
      return new Response(JSON.stringify({
        success: false,
        error: 'Unauthorized'
      } as APIResponse), {
        status: 401,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    const repoName = url.searchParams.get('repo');

    if (!repoName) {
      return new Response(JSON.stringify({
        success: false,
        error: 'Missing repository name'
      } as APIResponse), {
        status: 400,
        headers: { 'Content-Type': 'application/json' }
      });
    }

    const githubUsername = process.env.GITHUB_USERNAME || 'Smietje77';
    const githubUrl = `https://github.com/${githubUsername}/${repoName}`;

    return new Response(JSON.stringify({
      success: true,
      data: {
        exists: false, // Would check via GitHub API
        url: githubUrl,
        message: 'Use GitHub MCP to verify repository existence'
      }
    } as APIResponse), {
      status: 200,
      headers: { 'Content-Type': 'application/json' }
    });

  } catch (error) {
    console.error('GitHub status check error:', error);

    return new Response(JSON.stringify({
      success: false,
      error: 'Status check failed'
    } as APIResponse), {
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
};
